version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: henny-kane-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - db
    networks:
      - henny-kane-network

  db:
    image: mysql:8.0
    container_name: henny-kane-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - henny-kane-network

networks:
  henny-kane-network:
    driver: bridge

volumes:
  mysql_data:
